# File generated by Flopy version 3.9.3 on 07/23/2026 at 17:00:17.
BEGIN options
  XT3D_OFF
END options

BEGIN griddata
  alh
    CONSTANT       0.20000000
  ath1
    CONSTANT       0.20000000
END griddata

