# File generated by Flopy version 3.10.0 on 08/01/2026 at 07:09:56.
BEGIN options
  XT3D_OFF
END options

BEGIN griddata
  alh
    CONSTANT       0.50000000
  ath1
    CONSTANT       0.50000000
END griddata

